version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET="secret"
      - DATABASE_URL="postgresql://alex:password@localhost:5432/daytoday?schema=public"
    command: npm run dev