version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    container_name: daytoday
    build: .
    image: daytoday
    command: npm run docker:start
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres"
      PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1
    links:
      - db
volumes:
  db:
    driver: local