
import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-5xl text-blue-300">Andrew's Realm</h1>
      </main>
    </div>
  )
}
